Sprint2
elagarrigue/AyDS21-AK-Zeus2 pull request #1
Opened 2021-05-03 14:55 UTC by Laureanodeluca

2021-05-03 23:13 UTC, elagarrigue requested changes
Además de los comentarios en el PR:
- El formato de la fecha no funciona cuando los datos vienen de la DB
- Faltó una breve descripción del PR (en `Conversation`)

2021-05-04 20:14 UTC, Laureanodeluca commented
Cambiamos la manera en la que el programa muestra las fechas de salida de las canciones dependiendo de la precisión brindada por la API de Spotify:

- Si la precisión es `day` entonces va a mostrar el formato `dd/mm/aaaa`
- Si la precisión es `month` entonces va a mostrar el formato `<nombre del mes>, <año>`
- Si la precisión es `year` entonces va a mostrar el formato `<año> (not a leap year)`, en caso de que el año no sea bisiesto, o  `<año> (leap year)` en caso de que si lo sea. 

**Correcciones**
- Eliminados los imports inútiles.
- Cambiado el nombre de `DateHelper` a `SongToReleaseDateStringMapper`.
- Cambiada la implementación de `SongToReleaseDateStringMapper`. Ahora es implementada por tres clases, una por cada tipo de precisión.
- Implementada una Factory que crea Mapeadores según el tipo de precisión de la canción.
- Arreglado el error que provocaba que el formateo de la fecha no funcione cuando estos vengan de la base de datos.

2021-05-05 11:25 UTC, elagarrigue requested changes
Buen trabajo. Algunos comentarios menores finales.

2021-05-05 11:25 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/ReleaseDateStringMapperFactory.kt
> +            else -> null
Antes que null, mejor un mapper por defecto. Si no hay presición, una mejor UX sería mostrar release date como viene

2021-05-05 11:25 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongDescriptionHelperImpl.kt
> +        return if (songToReleaseDateStringMapper != null) {
Si `songToReleaseDateStringMapper` es null no se muestra nada en la pantalla... Esto es un smell de comportamiento, sólo debería afectar a la fecha, no a toda la descripción de la canción.

2021-05-05 11:25 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongToReleaseDateStringMapper.kt
> +        return "${dateComponents[2]}/${dateComponents[1]}/${dateComponents[0]}"
Acceder a los elementos del array es poco clean, hay que hacer un mapeo mental. Mejor agregar variables intermedias para que sea más claro:
```suggestion
        val year = dateComponents[0]
        val month = dateComponents[1]
        val day =  dateComponents[2]
        return "$day/$month/$year"
```
Un detalle, podemos confiar en el factory y sabemos que siempre vamos a tener 3 elementos. En otro caso, faltaría el checkeo de cantidad de elementos para evitar una excepción en ejecución.

2021-05-05 11:25 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongToReleaseDateStringMapper.kt
> +        return (when (partes[1]) {
Agregar variables intermedias day y month

2021-05-05 11:25 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongToReleaseDateStringMapper.kt
> +        return (when (partes[1]) {
Se puede eliminar la duplicacion `+ month`  
```
return "${when (month) {
                  "01" -> .....
             },  $month"
}
           
```

2021-05-05 11:25 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongToReleaseDateStringMapper.kt
> +    override fun map(song: Song): String = if (leapYear(song.releaseDate.toInt())) "${song.releaseDate} (Leap Year)" else "${song.releaseDate} (Not a leap year)"
Toda la lógica en una línea es algo dificil de leer y se esta  duplicando la 1er parte del string

2021-05-05 16:33 UTC, FaustoFe commented
Arreglamos los comentarios menores finales.

2021-05-05 18:40 UTC, elagarrigue requested changes
Últimos detalles

2021-05-05 18:40 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongDescriptionHelperImpl.kt
> +        val songToReleaseDateStringMapper = ReleaseDateStringMapperFactory().get(song)
no cumple con inversión de dependencias, inyectar la instancia via constructor y definir una interfaz para no depender de la clase concreta

2021-05-05 18:40 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/ReleaseDateStringMapperFactory.kt
> +class ReleaseDateStringMapperFactory {
Extraer interfaz para cumplir con ID

2021-05-05 19:49 UTC, IvanSandiu commented
Cambios detallados en la ultima corrección.

2021-05-05 21:17 UTC, elagarrigue requested changes
Cambios menores finales. Todavia falta la descripción del PR...

2021-05-05 21:17 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/ReleaseDateStringMapperFactory.kt
> +class ReleaseDateStringMapperFactoryImpl : ReleaseDateStringMapperFactory {
Debería ser `internal`

2021-05-05 21:17 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongDescriptionHelperImpl.kt
> +                            "Release Date: ${songToReleaseDateStringMapper.map(song)} "
Minor, la variable `songToReleaseDateStringMapper` no agrega mucho y se usa una vez, se puede hacer inline:
```
"Release Date: ${releaseDateStringMapperFactory.get(song).map()} "
```

2021-05-05 21:17 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/home/view/SongToReleaseDateStringMapper.kt
> +}
Se puede eliminar el parámetro `song` de la función map, ya que cuando creamos el maper necesitamos ese mismo objeto

```suggestion
interface SongToReleaseDateStringMapper {
    fun map(): String
}

internal class SongToGenericReleaseDateStringMapper(private song: Song) :SongToReleaseDateStringMapper{
    override fun map():String{
        return song.releaseDate
    }
}
```

2021-05-06 13:58 UTC, Laureanodeluca commented
- Agregada la etiqueta `internal` a la implementación de `ReleaseDateStringMapperFactory`
- En la clase `SongDescriptionHelperImpl`, el mapeo de la fecha de salida fue hecho de manera inline.
- Eliminado el parámetro `song` de la función `map` en la clase `SongToReleaseDateStringMapper`. Ahora se debe pasar la canción por el constructor.

2021-05-06 15:29 UTC, elagarrigue approved these changes
Ahí quedó :+1:

2021-05-06 15:30 UTC, merged