Java a kotlin
elagarrigue/AyDS21-AK-Zeus2 pull request #2
Opened 2021-05-14 22:26 UTC by Laureanodeluca

### Refactorización de Java a Kotlin
Se refactorizaron las clases `OtherInfoWindow` y `DataBase`. Se pasaron las clases de Java a Kotlin.

**En la clase OtherInfoWindow**
- Se le cambió el nombre a la función `getArtistInfo()` a `showArtistInfo()`.
- Separada la nueva función `showArtistInfo()` en las siguientes funciones:
              `getArtistInfo()`: Obtiene la información de un artista.
              `getInfoWikipediaApi()`: Obtiene la información de un artista desde la api de Wikipedia.
              `updateDescriptionText()`: Actualiza el texto de descripción del artista
              `initListeners()`: Inicializa el botón de "View Full Article". 
              `saveArtistDb()`: Guarda la información de un artista en la base de datos local.
              `loadDefaultImage()`: Carga el logo de wikipedia.
              `getWikipediaApi()`: Genera una instancia de WikipediaAPI.
- Refactorizado el companion object.
- Eliminados los comentarios innecesarios

**En la clase DataBase**
- Se crearon constantes para las columnas de la base de datos.
- Se eliminó el companion object generado por kotlin.
- Eliminada la función `test()`
- Eliminados los imports inútiles.

2021-05-14 22:28 UTC, Laureanodeluca commented
Encontramos una porción de código que dice:

`artistDescriptionText.text = Html.fromHtml(artistInfoText)`

Android Studio nos lo marca como un warning, con el siguiente mensaje:

`'fromHtml(String!): Spanned!' is deprecated. Deprecated in Java`

¿Lo dejamos?

2021-05-17 13:10 UTC, elagarrigue requested changes

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +    private val db = this.readableDatabase
eliminar

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +        return if (items.isEmpty()) null else items[0]
```suggestion
        return items.firstOrNull()
```

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +        val projection = arrayOf(ID_COLUMN, ARTIST_COLUMN, INFO_COLUMN)
constante

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +class OtherInfoWindow : AppCompatActivity() {
Buena practica usar sufijo Activity

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        showArtistInfo(intent.getStringExtra(ARTIST_NAME_EXTRA))
mover el parametro a la fun

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                .baseUrl("https://en.wikipedia.org/w/")
constante

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    }
SRP

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            urlWikipedia = "https://en.wikipedia.org/?curid=$pageid"
constante

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            val query = jobj["query"].asJsonObject
propiedades de json constante

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            loadDefaultImage()
mover a sub fun

2021-05-17 13:10 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        builder.append("<html><div width=400>")
constante

2021-05-18 19:03 UTC, elagarrigue requested changes

2021-05-18 19:03 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            artistInfoText = "[*]$artistInfoText"
constante para [*]

2021-05-18 19:03 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindowDataBase.kt
> +
Salto de línea extra

2021-05-19 15:05 UTC, Laureanodeluca commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +
No entendemos este comentario. ¿No es necesario llamar al servicio cada vez que se quiera buscar un elemento? ¿Cómo se obtendrían los datos de otra manera?

2021-05-19 15:08 UTC, Laureanodeluca commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +const val WIKIPEDIA_BASE_URL= "https://en.wikipedia.org/w/"
¿Cómo estaría bien indentada una clase? ¿Por qué está mal indentada actualmente?

2021-05-19 15:15 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +
`getJsonQuery()` hace la llamada al servicio externo. Estan haciendo esa llamada varias veces, debería hacerse sólo una vez y utilizar el resultado

2021-05-19 15:16 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +const val WIKIPEDIA_BASE_URL= "https://en.wikipedia.org/w/"
Falta el espacio entre el nombre de la constante y el `=`. Auto indentar la clase lo soluciona

2021-05-20 11:14 UTC, merged