MVC
elagarrigue/AyDS21-AK-Zeus2 pull request #3
Opened 2021-06-05 01:02 UTC by Laureanodeluca

### Reestructuración de MoreDetails
- Reestructuración del paquete `MoreDetails` para satisfacer la arquitectura MVC. 
- `Model`: Cuenta con todas las clases pertinentes al modelado de los articulos de Wikipedia: su repositorio local y su repositorio externo.
- `View`: Cuenta con toda la parte de la visualización de la vista de `MoreDetails`. 
- `Controller`: Cuenta con las clases pertinentes al controlador de `MoreDetails`.

### Diagrama de clases
La nueva estructura sigue el siguiente diagrama de clases
![image](https://user-images.githubusercontent.com/41490085/120874959-894d6000-c57f-11eb-8245-40bf248d0aed.png)

2021-06-06 13:48 UTC, elagarrigue requested changes
Diagrama:
- Agregar el paquete more details y los sub paquetes 
- Agregar las relaciones indirectas por los observers

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/AndroidManifest.xml
>          <activity android:name="ayds.zeus.songinfo.moredetails.fulllogic.OtherInfoActivity"
Eliminar la definición de esta actividad

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/controller/MoreDetailsController.kt
> +    }
No quedó bien formateada la clase

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/entities/Article.kt
> +    val article: String
El nombre de la propiedad es algo confuso (se llama igual que la clase)

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/external/wikipedia/info/WikipediaAPI.kt
> +            @Query("srsearch") artist: String?
formato incorrecto

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/external/wikipedia/info/WikipediaInfoModule.kt
> +    private val WIKIPEDIA_TO_ARTICLE_RESOLVER: WikipediaToArticleResolver= JsonToArticleResolver()
Nombre en camel case, es una propiedad, no una constante.

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/wikipedia/sqldb/WikipediaLocalStorageImpl.kt
> +    override fun getArtistInfo(artist: String): WikipediaArticle? {
Es buena práctica utilizar el mismo nombre de parámetro sobre escrito.

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/wikipedia/sqldb/WikipediaLocalStorageImpl.kt
> +        val items: MutableList<String> = ArrayList()
Dead code

2021-06-06 13:48 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/ArticleTextHelperImpl.kt
> +                .replace("(?i)" + term!!.toRegex(), "<b>" + term.toUpperCase(Locale.ROOT) + "</b>")
No es el mismo nivel de abstracción

2021-06-06 22:07 UTC, elianagk commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/wikipedia/sqldb/WikipediaLocalStorageImpl.kt
> +    override fun getArtistInfo(artist: String): WikipediaArticle? {
Hola, no entendemos el comentario.

2021-06-07 12:56 UTC, FaustoFe commented
Actualización del diagrama de clases
![MVC moredetails](https://user-images.githubusercontent.com/51035010/121017494-b7939100-c773-11eb-975f-34828a340f66.jpg)

2021-06-07 13:19 UTC, FaustoFe commented
Actualización del diagrama de clases:
![Diagrama moredetails](https://user-images.githubusercontent.com/51035010/121023637-d8f77b80-c779-11eb-904f-57c3a6494d83.jpg)

2021-06-07 13:54 UTC, Laureanodeluca commented
@elagarrigue Revisando si funcionaba el `ArticleTextHelper` después de haber hecho los cambios como vimos en el scrum de hoy, nos dimos cuenta de que no funcionaba, imprimía en la view siempre `kotlin.Unit`. El código estaba así: 
![image](https://user-images.githubusercontent.com/41490085/121028954-97b59a80-c77e-11eb-81f5-04de9a318555.png)

Revisandolo, lo cambiamos de esta manera:
![image](https://user-images.githubusercontent.com/41490085/121029085-b025b500-c77e-11eb-9612-2e67df5e5268.png)

y ahora funciona normalmente. ¿Lo dejamos así?

2021-06-07 14:43 UTC, elagarrigue commented
El problema es que `textToBold` devuelve Unit, no String. Cambienlo de la siguiente manera:
``` 
private fun String.textToBold(term: String?) =
        this
            .replace("'", " ")
            .replace("\n", "<br>")
            .replace("(?i)" + term!!.toRegex(), "<b>" + term.toUpperCase(Locale.ROOT) + "</b>")
```

2021-06-07 14:48 UTC, Laureanodeluca commented
> El problema es que `textToBold` devuelve Unit, no String. Cambienlo de la siguiente manera:
>...

Genial, ahi lo cambiamos. Gracias!

2021-06-08 13:27 UTC, elagarrigue approved these changes
Muy bien, ahí quedó 👍🏽

2021-06-08 13:27 UTC, merged